export { default as GameManager } from './components/GameManager';
export { useQuestions } from './hooks/useQuestions';
export { useSoundEffects } from './hooks/useSoundEffects';
export { useSoundSystem } from './hooks/useSoundSystem';
export { environmentConfigs, TOTAL_ENVIRONMENTS } from './config/environments';
export { getCampusList as apiGetCampusList } from '@/models/services/campus.service';
export { getCursoList as apiGetCursoList } from '@/models/services/curso.service';
export { getPerguntasByQuiz as apiGetPerguntasByQuiz } from '@/models/services/pergunta.service';
export { getAlternativasByPergunta as apiGetAlternativas } from '@/models/services/alternativa.service';
export type { EnvironmentId } from './config/environments';
export type { DbQuestion, DbAlternative } from './hooks/useQuestions';
